version: "3.7"

services:
  book-track-database:
    image: postgres:14.3
    environment:
      - POSTGRES_DB=booktrack
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - book-track-network
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  book-track-app:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - book-track-database
    networks:
      - book-track-network
    environment:
      - DATABASE_URL=posgres://admin:admin@book-track-database:5432/booktrack

networks:
  book-track-network:
    driver: bridge
